# Generated by Django 5.2.7 on 2026-01-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_delete_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='goods',
            field=models.CharField(default='', max_length=2048),
        ),
    ]
