# Generated by Django 5.2.7 on 2026-01-26 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('BUY', 'Buy'), ('WALLET', 'Wallet')], default='BUY', max_length=10),
        ),
    ]
