# Generated by Django 5.2.7 on 2025-11-04 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0003_alter_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank_Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('paymentid', models.CharField(max_length=256)),
                ('payment_on', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='payments.payment')),
            ],
        ),
    ]
