# Generated by Django 5.1.1 on 2024-09-08 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0020_alter_product_monetary_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank_Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('peymentid', models.CharField(max_length=256)),
                ('shopping_cart', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.shopping_cart')),
            ],
        ),
    ]
