# Generated by Django 5.1.1 on 2024-09-08 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zarinpal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank_transaction',
            name='peymentid',
            field=models.CharField(max_length=512),
        ),
    ]
