# Generated by Django 5.1.1 on 2024-09-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zarinpal', '0002_alter_bank_transaction_peymentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank_transaction',
            name='peymentid',
            field=models.CharField(max_length=256),
        ),
    ]
