# Generated by Django 5.1.1 on 2024-09-18 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_remove_shopping_cart_user_and_more'),
        ('zarinpal', '0003_alter_bank_transaction_peymentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank_transaction',
            name='shopping_cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.shoppingcart'),
        ),
    ]
