# Generated by Django 5.2.7 on 2025-11-04 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('ZP', 'ZarinPal'), ('PP', 'PayPal'), ('TON', 'Toncoin'), ('IP', 'InPlacePayment')], max_length=3),
        ),
    ]
