# Generated by Django 5.2.7 on 2026-01-07 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_payment_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('ZP', 'ZarinPal'), ('PP', 'PayPal'), ('TON', 'Toncoin'), ('IP', 'InPlacePayment'), ('WAL', 'InternalWallet')], max_length=3),
        ),
    ]
