# Generated by Django 5.2.7 on 2026-01-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_payment_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('ZP', 'ZarinPal'), ('TON', 'Toncoin'), ('IP', 'InPlacePayment'), ('WAL', 'InternalWallet')], max_length=3),
        ),
    ]
