# Generated by Django 5.2.7 on 2026-01-22 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_alter_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='balance_type',
            field=models.CharField(choices=[('DOLER', 'Doler'), ('TONCOIN', 'Toncoin'), ('RIAL', 'Rial')], default='RIAL', max_length=10),
        ),
    ]
