# Generated by Django 5.2.7 on 2026-01-25 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_alter_wallet_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=30),
        ),
    ]
