# Generated by Django 5.2.7 on 2025-11-07 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TonCoin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tonpaymentrequest',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tonpaymentrequest',
            name='mached_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_request', to='TonCoin.tontransaction'),
        ),
    ]
